# Prometheus configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'distributed-sync-nodes'
    static_configs:
      - targets:
          - 'node1:9090'
          - 'node2:9090'
          - 'node3:9090'
        labels:
          cluster: 'distributed-sync'

  - job_name: 'redis'
    static_configs:
      - targets:
          - 'redis:6379'
